# -*- coding: utf-8 -*-
"""connections_stations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EFcUsvNcR9H4-V6qxO9MHnrA1ykHqXiG
"""

import pandas as pd

df= pd.read_html('/content/data.html')
csv = ('stations.csv')

df[0].to_csv(csv,index=False)

df1 = pd.read_csv('stations.csv')
df1.head()

csv1 =('connections.csv')
df[1].to_csv(csv1,index=False)
df2 = pd.read_csv('connections.csv')
df2.head()